name: Go CI/CD Workflow

on:
  push:
    branches: [hoved]
    paths:
      - "apis/trips/**"
  pull_request:
    paths:
      - "apis/trips/**"

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apis/trips
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.11

    - name: Go Mod Get
      run: go get

    - name: Test
      run: go test ./tests
    
    - name: Open Issue
      if: steps.tests.outputs.failed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: JasonEtco/create-an-issue@v2

    - name: Build
      run: go build -v ./...

