name: Node.js CI

on:
  push:
    branches: [ hoved ]
    paths:
      - "apis/userprofile/**"
  pull_request:
    paths:
      - "apis/userprofile/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apis/userprofile

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '8'
        cache: 'npm'
        cache-dependency-path: ./apis/userprofile/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
