name: Node.js CI

on:
  push:
    branches: [ hoved ]
    paths:
      - "apis/userprofile/**"
  pull_request:
    paths:
      - "apis/userprofile/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apis/userprofile

    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'
        
    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
